name: Build Binaries

# Have this run manually
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The mac version
  macOS:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

      # will need this for `make test`
#       - name: Install newer bash
#         run: brew install bash

      - name: Setup GNAT Install Directory 
        run: mkdir gnat

      - name: Download GNAT 
        run: wget https://master.dl.sourceforge.net/project/gnuada/GNAT_GCC%20Mac%20OS%20X/10.1.0/native/gcc-10.1.0-x86_64-apple-darwin15-bin.tar.bz2 -O gnat.tar.bz2
        
      - name: Extract GNAT
        run: tar -xvf gnat.tar.bz2 --strip-components 1 -C gnat

      - name: Install GNAT
        # This hardcoding is probably not the best idea.
        run: cd gnat && make ins-all prefix=$HOME/gcc version=10.1.0 built_prefix="/Volumes/Miscellaneous/tmp/opt/gcc-10.1.0" machine=x86_64-apple-darwin15

      - name: Update path
        run: echo 'PATH="$HOME/gcc/bin:$PATH"' >> $HOME/.bash_profile

      - name: Download whitakers-words
        run: git clone --depth=1 https://github.com/mk270/whitakers-words

      - name: Make whitakers-words
        # Replace with this line when on main branch
#         run: cd $ GITHUB_WORKSPACE && make
        run: cd whitakers-words && make

        # TODO: Change this actual tests once they will run on macOS
      - name: Test simple word
        run: ./bin/words victori

  linux:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

      - name: Install tools
        run: sudo apt-get install gnat gprbuild

      - name: Download ada code
        run: git clone --depth=1 https://github.com/mk270/whitakers-words

      - name: Make ada code
        # Replace with this line when on main branch
#         run: cd $ GITHUB_WORKSPACE && make
        run: cd whitakers-words && make
      
      - name: Make tests
        run: make test
