name: Build Binaries

# Have this run manually
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The mac version
  macOS:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

      # will need this for `make test`
      # - name: Install newer bash
      #   run: brew install bash

      - name: Setup Directories 
        run: mkdir gnat

      - name: Download GNAT 
        run: wget https://master.dl.sourceforge.net/project/gnuada/GNAT_GCC%20Mac%20OS%20X/10.1.0/native/gcc-10.1.0-x86_64-apple-darwin15-bin.tar.bz2 -O gnat.tar.bz2
        
      - name: Extract GNAT
        run: tar -xvf gnat.tar.bz2 --strip-components 1 -C gnat
        
      - name: Install GNAT
        run: cd gnat && make ins-all prefix=$HOME/gcc version=10.1.0 built_prefix="/Volumes/Miscellaneous/tmp/opt/gcc-10.1.0" machine=x86_64-apple-darwin15

      - name: Download ada code
        run: git clone --depth=1 https://github.com/mk270/whitakers-words

      - name: Make ada code
        run: cd whitakers-words && make
