name: Build Binaries

# Have this run manually
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The mac version
  macOS:
    runs-on: macos-latest

    steps:
      # - name: Download ada code
        # run: |
          # git clone --depth=1 https://github.com/mk270/whitakers-words
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

      - name: Install newer bash
        run: brew install bash

      - name: Install GNAT
        run: |
          mkdir gnat
          wget https://master.dl.sourceforge.net/project/gnuada/GNAT_GCC%20Mac%20OS%20X/10.1.0/native/gcc-10.1.0-x86_64-apple-darwin15-bin.tar.bz2 -O gnat.tar.bz2,
          tar -xvf gnat.tar.bz2 --strip-components 1 -C gnat,
          cd gnat,
          ./doinstall.
        # TODO: how do I pass it commands??

      - name: Make ada code
        run: |
          cd whitakers-words,
          make.
