# This is a basic workflow to help you get started with Actions

name: Build with Ada

# Mac compiles are expensive, setup as only on demand for now
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Download ada code
        # run: |
          # git clone --depth=1 https://github.com/mk270/whitakers-words
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

      - name: Install newer bash
        run: brew install bash

      - name: Install GNAT
        run: |
          wget https://master.dl.sourceforge.net/project/gnuada/GNAT_GCC%20Mac%20OS%20X/10.1.0/native/gcc-10.1.0-x86_64-apple-darwin15-bin.tar.bz2 -O gnat.tar.bz2,
          tar -xvf gnat.tar.bz2,
          cd gnat,
          ./doinstall.
        # TODO: how do I pass it commands??

      - name: Make ada code
        run: |
          cd whitakers-words,
          make.
