name: Windows

on:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest

    steps:        
      - name: GNAT Install
        run: |
          # https://www.msys2.org/wiki/MSYS2-installation/
          wget http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20200903.tar.xz -UseBasicParsing -OutFile msys2.tar.xz
          Expand-7Zip msys2.tar.xz msys2
          cd .\msys2
          # TODO Finish installing msys and mingw
          pacman -Syuu
          # https://packages.msys2.org/package/mingw-w64-x86_64-gcc-ada
          pacman -S mingw-w64-x86_64-gcc-ada
          # https://packages.msys2.org/package/mingw-w64-x86_64-gprbuild
          pacman -S mingw-w64-x86_64-gprbuild

      - name: Whitakers-Words Checkout
        uses: actions/checkout@v2
        with: 
          path: 'whitakers-words'

      - name: Whitakers-Words Build and Test
        run: |
          cd whitakers-words
          make all
          make test

      - name: Binary Organize
        run: |
          mkdir words
          mv whitakers-words/LICENCE.txt    words/
          mv whitakers-words/bin            words/
          mv whitakers-words/ADDONS.LAT     words/
          mv whitakers-words/DICTFILE.GEN   words/
          mv whitakers-words/EWDSFILE.GEN   words/
          mv whitakers-words/INDXFILE.GEN   words/
          mv whitakers-words/INFLECTS.SEC   words/
          mv whitakers-words/STEMFILE.GEN   words/
          mv whitakers-words/UNIQUES.LAT    words/
      
      - name: Binary Export
        uses: actions/upload-artifact@v2
        with:
          name: words-Windows-x64
          path: |
            words
