name: Windows

on:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - name: GNAT Install
        shell: powershell
        run: |
          cd C:\msys64\
          
          # Running the update twice on purpose
          .\msys2.exe pacman -Syuu --noconfirm
          .\msys2.exe pacman -Syuu --noconfirm
          
          # https://packages.msys2.org/package/mingw-w64-x86_64-gcc-ada
          # https://packages.msys2.org/package/mingw-w64-x86_64-gprbuild
          # https://packages.msys2.org/package/mingw-w64-x86_64-make
          
          .\msys2.exe pacman --noconfirm -S mingw-w64-x86_64-gcc-ada
          .\msys2.exe pacman --noconfirm -S mingw-w64-x86_64-gprbuild
          .\msys2.exe pacman --noconfirm -S mingw-w64-x86_64-make
          .\msys2.exe pacman --noconfirm -S diffutils


      - name: Whitakers-Words Checkout
        uses: actions/checkout@v2
        with: 
          path: 'whitakers-words'

      - name: Whitakers-Words Build and Test
        shell: powershell
        run: |
          # Make alias for build since it doesn't get added to path
          Set-Alias -Name make -Value C:\msys64\mingw64\bin\mingw32-make.exe
          
          cd whitakers-words
          
          make all
          make test

      - name: Binary Organize
        shell: powershell
        run: |
          mkdir words
          mv whitakers-words/LICENCE.txt    words/
          mv whitakers-words/bin            words/
          mv whitakers-words/ADDONS.LAT     words/
          mv whitakers-words/DICTFILE.GEN   words/
          mv whitakers-words/EWDSFILE.GEN   words/
          mv whitakers-words/INDXFILE.GEN   words/
          mv whitakers-words/INFLECTS.SEC   words/
          mv whitakers-words/STEMFILE.GEN   words/
          mv whitakers-words/UNIQUES.LAT    words/
      
      - name: Binary Export
        uses: actions/upload-artifact@v2
        with:
          name: words-Windows-x64
          path: |
            words
