# This is a basic workflow to help you get started with Actions

name: Windows

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  Windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
#       - uses: actions/checkout@v2
        
      - name: GNAT Install
        # TODO

      - name: Whitakers-Words Checkout, Build, Test
        run: |
          git clone --depth=1 https://github.com/Alex-Vasile/whitakers-words
          cd whitakers-words
          make all
          make test

      - name: Binary Organize
        run: |
          mkdir words
          mv whitakers-words/LICENCE.txt    words/
          mv whitakers-words/bin            words/
          mv whitakers-words/ADDONS.LAT     words/
          mv whitakers-words/DICTFILE.GEN   words/
          mv whitakers-words/EWDSFILE.GEN   words/
          mv whitakers-words/INDXFILE.GEN   words/
          mv whitakers-words/INFLECTS.SEC   words/
          mv whitakers-words/STEMFILE.GEN   words/
          mv whitakers-words/UNIQUES.LAT    words/
      
      - name: Binary Export
        uses: actions/upload-artifact@v2
        with:
          name: words-Windows-x64
          path: |
            words
